server:
  port: 8989
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: cmfz/dao/*Dao.xml
  type-aliases-package: cmfz.entity

#server.port=8989
#server.context-path=/cmfz
#server.jsp-servlet.init-parameters.development=true
#spring.mvc.view.suffix=.jsp
#spring.mvc.view.prefix=/
#spring.http.encoding.charset=utf-8
#spring.http.encoding.force=true
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.url=jdbc:mysql://localhost:3306/maven
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#mybatis.mapper-locations=com/baizhi/dao/*Dao.xml
#mybatis.type-aliases-package=com.baizhi.entity
